/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
      },
      colors: {
        brand: {
          bg: '#F4F6FA',
          surface2: '#EEF1F7',
          primary: '#1A6BFF',
          'primary-light': '#E8F0FF',
          accent: '#FF6B35',
          'accent-light': '#FFF0EA',
          border: '#E2E8F0',
        },
        ath: {
          base: 'var(--ath-bg-base)',
          surface: 'var(--ath-bg-surface)',
          elevated: 'var(--ath-bg-elevated)',
          accent: 'var(--ath-accent)',
          'accent-hover': 'var(--ath-accent-hover)',
          'accent-text': 'var(--ath-accent-text)',
          'accent-surface': 'var(--ath-accent-surface)',
          border: 'var(--ath-border)',
          'border-accent': 'var(--ath-border-accent)',
          'on-accent': 'var(--ath-on-accent)',
          'bg-accent': 'var(--ath-bg-accent)',
          inset: 'var(--ath-bg-inset)',
          'text-primary': 'var(--ath-text-primary)',
          'text-secondary': 'var(--ath-text-secondary)',
          'text-muted': 'var(--ath-text-muted)',
        },
        coach: {
          base: 'var(--coach-bg-base)',
          surface: 'var(--coach-bg-surface)',
          elevated: 'var(--coach-bg-elevated)',
          inset: 'var(--coach-bg-inset)',
          accent: 'var(--coach-accent)',
          'accent-hover': 'var(--coach-accent-hover)',
          'accent-light': 'var(--coach-accent-light)',
          'accent-surface': 'var(--coach-accent-surface)',
          border: 'var(--coach-border)',
          'on-accent': 'var(--coach-on-accent)',
          'text-primary': 'var(--coach-text-primary)',
          'text-secondary': 'var(--coach-text-secondary)',
          'text-muted': 'var(--coach-text-muted)',
        },
      },
    },
  },
  plugins: [],
}